### ISSUE TITLE
Changing Mayors

### ISSUE THREAD

**Issue by merriec** [jmhertlein/MCTowns#80]
Is there a way to change the mayors of the towns without deleting the entire town?

**Comment by jmhertlein** [comment]
/town setmayor <resident name>

Must be run by either an admin, or the current mayor

**Comment by merriec** [comment]
Thanks so much for this.  Using it on a fairly large scale.  We'd like a
mayor to have control of a fairly large area with separate villages.  Is
there an assistant option for control of smaller villages without
separating banks?

**Comment by merriec** [comment]
I should explain that the area in question is a 4000x4000 square.  We love
the simplicity of your plugin,  especially as we anticipate players who
perhaps don't have much experience with them.  Each square is supposed to
represent a kingdom with one leader.  Within that square can be smaller
towns,  but we'd like each square to keep their own bank and not separate
out too much.  So we're trying to figure out if territory or town would be
the better option for the giant square.

**Comment by jmhertlein** [comment]
Mayors can add assistants that act just like mayors, but they cannot
add/remove the mayor and can't add/remove other assistants. There's no way
to tie an assistant to just one territory, though.

**Comment by merriec** [comment]
Sorry one more quick question. Is there a way to stop a territory from
going down to bedrock?

**Comment by hockeymikey** [comment]
How far down do you want to limit the territory to?

At the moment no because selection is handled by WorldEdit so you'll want to make a wrapper for WorldEdit like what I did or I could maybe add it into the one I made, that's an opinion.

**Comment by jmhertlein** [comment]
Right now, theres no analogue for the large square. Towns all have exactly one bank and one major, but can have many territories and assistants. Territories are used so that admins can cordon off land for the mayors to have WorldGuard control over (through MCTowns, not directly, of course). Mayors can then split territories into as many plots as they want, without requiring more work from admins.

MCTowns doesn't try to do anything that groups towns together, which is what you would need for your 4000x4000 square. So, that would need to be informal (keep a forum thread or a bunch of signs that say who is in what kingdom). 

There has been some interest in a feature like this, usually asking for "nations" or "kingdoms" to group towns together. But basically all it would be is a list of which towns are in which kingdom. 

So, I might get around to such a feature eventually, but since it's mainly a book-keeping feature, it's not too high of a priority at the moment.

**Comment by jmhertlein** [comment]
And, no, there is no way to prevent an admin from making a territory go to bedrock right now.

If an admin doesn't want it to expand vertically, they just need to not use //expand very while making the region. Use //expand 100 up or something similar.
